name: test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "4f4a7dcb49837dc01e72f0d6d29a1041f28e534e"

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: im a stats nerd
        run: du -sh _site
